controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 2.5        # Increased from 1.0 to 2.5 (much faster!)
      max_vel_y: 0.0
      max_vel_theta: 6.0    # Increased from 3.0 to 6.0 (much faster rotation!)
      min_speed_xy: 0.1     # Reduced from 1.0 to 0.1 for better low-speed control
      max_speed_xy: 2.5     # Increased from 0.6 to 2.5 (much faster!)
      min_speed_theta: 0.0
      acc_lim_x: 8.0        # Increased from 4.0 to 8.0 (much faster acceleration!)
      acc_lim_y: 0.0
      acc_lim_theta: 10.0   # Increased from 5.0 to 10.0 (much faster turning!)
      decel_lim_x: -8.0     # Increased from -4.0 to -8.0 (much faster deceleration!)
      decel_lim_y: 0.0
      decel_lim_theta: -10.0 # Increased from -5.0 to -10.0 (much faster turning decel!)
      # Add missing critics
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
    
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.05